sudo: true
dist: xenial
services:
  - docker

before_install:
  - docker build -t bionitio-rust .

script:
  - docker run --entrypoint /bionitio/.travis/unit-test.sh bionitio-rust
  - docker run --entrypoint /bionitio/functional_tests/bionitio-test.sh bionitio-rust -p bionitio -d /bionitio/functional_tests/test_data -v  
