sudo: true
dist: trusty

language: rust

before_install:
  - ./.travis/install-dependencies.sh 

script:
  - ./functional_tests/bionitio-test.sh -p ~/.cargo/bin/bionitio-rs -d functional_tests/test_data
  - ./.travis/unit-test.sh
